### ISSUE TITLE
Safari latest cannot find airtap.local

### ISSUE THREAD

**Issue by jzombie** [airtap/sauce#11]
When uncommenting Safari in the following configuration, it seems to not be able to resolve the airtap.local host entry (failing after about 5 minues), while the other browser can.

```yml
sauce_connect: true
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  # - name: safari
  #  version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
providers:
  - airtap-sauce
```

Running airtap 4.0.4 and airtap-sauce 1.1.2.

The console eventually errors like so:

```
Retrying due to Error: [get("http://airtap.local:34751/airtap")] ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/jeremy/Projects/phantom-core/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:519:28)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}

```

The SauceLabs logs are:

```
[
  {
    "screenshot": 0,
    "suggestion_values": [],
    "start_time": 1639428087.496261,
    "request": {
      "desiredCapabilities": {
        "javascriptEnabled": true,
        "browserName": "safari",
        "safari.options": {}
      }
    },
    "result": {
      "browserVersion": "15.1",
      "safari:platformVersion": "12.0.1",
      "safari:diagnose": false,
      "strictFileInteractability": false,
      "safari:automaticInspection": false,
      "acceptInsecureCerts": false,
      "platformName": "macOS",
      "safari:automaticProfiling": false,
      "browserName": "Safari",
      "setWindowRect": true,
      "webkit:WebRTC": {
        "DisableICECandidateFiltering": false,
        "DisableInsecureMediaCapture": false
      },
      "safari:useSimulator": false,
      "safari:platformBuildVersion": "21A559"
    },
    "duration": 3.192833185195923,
    "path": "/session",
    "hide_from_ui": false,
    "between_commands": null,
    "visual_command": false,
    "HTTPStatus": 200,
    "suggestion": null,
    "in_video_timeline": 1.5,
    "method": "POST",
    "statusCode": 0
  },
  {
    "screenshot": 1,
    "suggestion_values": [],
    "start_time": 1639428091.541933,
    "request": {
      "url": "http://airtap.local:34751/airtap"
    },
    "result": {
      "message": "Automation Server Error -- Selenium didn't complete your last command on time.\nFor help, please check https://docs.saucelabs.com/dev/error-messages"
    },
    "duration": 300.00740098953247,
    "path": "url",
    "hide_from_ui": false,
    "between_commands": 0.8528389930725098,
    "visual_command": false,
    "HTTPStatus": 408,
    "suggestion": null,
    "in_video_timeline": 5.5,
    "method": "POST",
    "statusCode": 21
  },
  {
    "screenshot": 1,
    "suggestion_values": [],
    "start_time": 1639428151.599126,
    "request": {
      "url": "http://airtap.local:34751/airtap"
    },
    "result": null,
    "duration": 239.9848439693451,
    "path": "url",
    "hide_from_ui": false,
    "between_commands": -239.9502079486847,
    "visual_command": false,
    "HTTPStatus": 200,
    "suggestion": null,
    "in_video_timeline": 65.25,
    "method": "POST",
    "statusCode": 0
  },
  {
    "screenshot": 1,
    "suggestion_values": [],
    "start_time": 1639428211.676261,
    "request": {
      "url": "http://airtap.local:34751/airtap"
    },
    "result": null,
    "duration": 179.93945407867432,
    "path": "url",
    "hide_from_ui": false,
    "between_commands": -179.9077091217041,
    "visual_command": false,
    "HTTPStatus": 200,
    "suggestion": null,
    "in_video_timeline": 125.75,
    "method": "POST",
    "statusCode": 0
  }
]
```

Link to failed test: https://app.saucelabs.com/tests/a4a02009876e415c8ca4911b31020795#1

**Comment by jzombie** [comment]
NOTE: This ONLY affects Mac Safari.  iOS Safari is working okay.

**Comment by vweevers** [comment]
Only safari latest, or any safari version?

**Comment by jzombie** [comment]
Assuming just latest.  Didn"t experience it last week.  Will update later
if I decide to pin it to a version.

**Comment by jzombie** [comment]
Final edit:  Disregard below.  It's an apparent error in my code because it doesn't have same issue in another repo which uses same configuration.  Leaving this here for historical purposes, only.

--------------------------

So, here's a potential update.  Safari iOS "latest" is now getting this (two attempts in a row).

`Retrying due to TimeoutError: Did not receive output from 'Sauce Labs iOS Safari on iOS 15.0 on iPhone XS Simulator' (5 minutes)`

Edit: This may be actually because of a bug in my code; not yet confirmed.  Will try to remember to confirm soon.

**Comment by vweevers** [comment]
I also see the same issue on Mac Safari 12 now, on two separate repos. And yeah, iOS is doing fine. No idea what it is, unfortunately.

**Comment by jzombie** [comment]
Hopefully it's an eventual resolvable Safari bug instead of some new security feature.
